name: Run UI Tests (Docker First)
on:
  repository_dispatch:
    types: [dotnet_deploy_success]


jobs:
  run-in-docker:
    name: Run in Docker Grid
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Selenium UI Tests on Docker Grid
        run: mvn test -DenvProfile=docker

  run-in-ci:
    name: Run in GitHub CI
    runs-on: ubuntu-latest
    needs: run-in-docker

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Run Selenium UI Tests in CI
        run: mvn test -DenvProfile=ci

  run-in-local:
    name: Run in Local Machinef
    runs-on: self-hosted
    needs: run-in-ci

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Run Selenium UI Tests in Local
        run: mvn test -DenvProfile=local
