name: Run Selenium After .NET Deployment

on:
  repository_dispatch:
    types: [dotnet_deploy_success]

jobs:
  selenium-tests:
    runs-on: self-hosted  # يدعم جهازك المحلي، ويعمل أيضًا على GitHub-hosted لو ضبطت runner group

    steps:
      - name: Checkout Test Project
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Detect Environment Profile
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "ENV_PROFILE=local" >> $GITHUB_ENV
          else
            echo "ENV_PROFILE=ci" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Run Selenium Tests
        run: mvn test -DenvProfile=${{ env.ENV_PROFILE }}
